name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hey!
        run: echo "Hey Fellow Dev"
      - name: Bye!
        run: echo "Bye bro"
      
